//
// Copyright 2020-2020 Tim Schmelter
//
// SPDX-License-Identifier: Apache-2.0
//

#if !canImport(ObjectiveC)
import XCTest

extension ArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayTests = [
        ("testDuplicateValues", testDuplicateValues),
        ("testEqual", testEqual),
        ("testSame", testSame),
        ("testUnequalElements", testUnequalElements),
        ("testUnequalLengths", testUnequalLengths),
    ]
}

extension SetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SetTests = [
        ("testEqual", testEqual),
        ("testSame", testSame),
        ("testUnequalElements", testUnequalElements),
        ("testUnequalLengths", testUnequalLengths),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayTests.__allTests__ArrayTests),
        testCase(SetTests.__allTests__SetTests),
    ]
}
#endif
